# https://blog.lelonek.me/how-to-use-elixir-with-docker-836c9b4a25b0
FROM elixir:latest

# Install npm
RUN apt update -y
RUN apt install npm -y
RUN apt install postgresql -y

# Install hex
RUN mix local.hex --force

# Install rebar
RUN mix local.rebar --force
